### ISSUE TITLE
How to make the data sense?

### ISSUE THREAD

**Issue by NmcX** [HalcyonWjr/Spiritualist-group16#2]
Our data analysis using NLTK could only yield these results for word frequency. How should this data be combined to visualise and present a complete story to the audience.

**Comment by nixuenimane** [comment]
Word frequency may be related to information about many places or people. I think it may be possible to search for information for some high-frequency names.

**Comment by miruru922** [comment]
Hi NmcX, I think we can create a lexicon of high-frequency words in an artificial way, where human language cannot be judged by absolute results. We can use it as a supplementary segment, based on word frequency statistics and analysis, to establish a link between the frequency of word changes and historical events, towards the creation of a result that people can read and understand.

**Comment by NoooraZ** [comment]
We could use word frequency to develop the data story from multiple perspectives and also to find how the story went over the entire time period.

**Comment by NmcX** [comment]
As words have different meanings in different contexts, word frequency statistics can only assist in the output of our final content. Just like @miruru922 said, we can explore external literature and original content based on high frequency words to sort out the stories of important people in the newspaper to present our data.
