### ISSUE TITLE
Chart style

### ISSUE THREAD

**Issue by nixuenimane** [HalcyonWjr/Spiritualist-group16#4]
Which chart style do you think is more suitable for displaying these data? Do we need to use some sophisticated models?

**Comment by miruru922** [comment]
I think a straightforward table is best. The point of visualising data is to make it more understandable. It is advisable to explain the data points that are of interest in the table and to explain them.

**Comment by NoooraZ** [comment]
The simpler, the better. Since we want to get our audience's interest in a short period of time.

**Comment by NmcX** [comment]
The visual style of the charts could be modelled on that of 19th century newspapers. This will highlight our theme.
